version: '3'

services:
    ibmq:
        build:
            context: ibmq
        restart: unless-stopped
        volumes:
            - ./ibmq/heisenberg:/ibmq/heisenberg
            - ./ibmq/qiskit-terra:/ibmq/qiskit-terra
    dwave:
        build:
            context: dwave
        restart: unless-stopped
        volumes:
            - ./dwave/dwave-demos:/demos
